name: send mail action

on:
  push:
    branches:
      - develop

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Send mail
        uses: ./
        with:
          message: Test of action completed successfully!
          to: aloeveraking@outlook.com
          from: alexismateod@outlook.com
