name: send mail action

on:
  push:
    branches:
      - develop

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Send mail
        uses: ./
        with:
          smtp-server: smtp.office365.com
          smtp-server-port: 25
          auth-user: a.mateo@caribemedia.com.do
          auth-password: ${{secrets.EMAIL_PASSWORD}}
          subject: elaborado
          body: que buena idea
          from: a.mateo@caribemedia.com.do
          to: a.mateo@caribemedia.com.do
          is-tls: true
